hey-url-challenge-code-dotnet/Models/AbstractBaseModel.cs
using System;

namespace hey_url_challenge_code_dotnet.Models
{
    public class AbstractBaseModel
    {
        public Guid Id { get; set; }
    }
}

hey-url-challenge-code-dotnet/Models/Url.cs
using System;
using System.Collections.Generic;

namespace hey_url_challenge_code_dotnet.Models
{
    public class Url : AbstractBaseModel
    {
        public string OriginalUrl { get; set; }
        public string ShortUrl { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public int Count { get; set; }

        public IList<UrlClickMetrics> ClickMetrics { get; set; } = new List<UrlClickMetrics>();
        public IList<UrlPlatformMetrics> PlatformMetrics { get; set; } = new List<UrlPlatformMetrics>();
        public IList<UrlBrowserMetrics> BrowserMetrics { get; set; } = new List<UrlBrowserMetrics>();
    }
}

hey-url-challenge-code-dotnet/Models/UrlBrowserMetrics.cs
using System;

namespace hey_url_challenge_code_dotnet.Models
{
    public class UrlBrowserMetrics : AbstractBaseModel
    {
        public UrlBrowserMetrics() { }

        public UrlBrowserMetrics(Url url, string browser)
        {
            this.Url = url;
            this.UrlId = url.Id;
            this.Browser = browser;
        }

        public string Browser { get; set; }
        public DateTime Date { get; set; } = DateTime.UtcNow.Date;
        public int Count { get; set; } = 0;

        public Guid UrlId { get; set; }
        public Url Url { get; set; }
    }
}

hey-url-challenge-code-dotnet/Models/UrlClickMetrics.cs
using System;

namespace hey_url_challenge_code_dotnet.Models
{
    public class UrlClickMetrics : AbstractBaseModel
    {
        public UrlClickMetrics() { }

        public UrlClickMetrics(Url url)
        {
            this.Url = url;
            this.UrlId = url.Id; 
        }

        public DateTime Date { get; set; } = DateTime.UtcNow.Date;
        public int Count { get; set; }

        public Guid UrlId { get; set; }
        public Url Url { get; set; }
    }
}

hey-url-challenge-code-dotnet/Models/UrlPlatformMetrics.cs
using System;

namespace hey_url_challenge_code_dotnet.Models
{
    public class UrlPlatformMetrics : AbstractBaseModel
    {
        public UrlPlatformMetrics() { }

        public UrlPlatformMetrics(Url url, string platform)
        {
            this.Url = url;
            this.UrlId = url.Id;
            this.Platform = platform;
        }

        public string Platform { get; set; }
        public DateTime Date { get; set; } = DateTime.UtcNow.Date;
        public int Count { get; set; } = 0;

        public Guid UrlId { get; set; }
        public Url Url { get; set; }
    }
}

hey-url-challenge-code-dotnet/ViewModels/ErrorViewModel.cs
namespace HeyUrlChallengeCodeDotnet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
        public string Title { get; set; }
        public string Message { get; set; }
    }
}

hey-url-challenge-code-dotnet/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using hey_url_challenge_code_dotnet.Models;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Url> Urls { get; set; }
    }
}

hey-url-challenge-code-dotnet/ViewModels/ShowViewModel.cs
using System.Collections.Generic;
using hey_url_challenge_code_dotnet.Models;

namespace hey_url_challenge_code_dotnet.ViewModels
{
    public class ShowViewModel
    {
        public Url Url { get; set; }
        public IDictionary<int, int> DailyClicks { get; set; }
        public IDictionary<string, int> BrowseClicks { get; set; }
        public IDictionary<string, int> PlatformClicks { get; set; }
    }
}

hey-url-challenge-code-dotnet/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace hey_url_challenge_code_dotnet.Controllers
{
    [Route("Error")]
    public class ErrorController : Controller
    {
        [Route("404")]
        public ActionResult NotFoundPage()
        {
            return View("404");
        }

        [Route("500")]
        public ActionResult InternalServerErrorPage()
        {
            return View("500");
        }
    }
}

hey-url-challenge-code-dotnet/Controllers/UrlsController.cs
using hey_url_challenge_code_dotnet.Exceptions;
using hey_url_challenge_code_dotnet.Service;
using hey_url_challenge_code_dotnet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shyjus.BrowserDetection;
using System;
using System.Threading.Tasks;

namespace HeyUrlChallengeCodeDotnet.Controllers
{
    [Route("/")]
    public class UrlsController : Controller
    {
        private readonly IBrowserDetector browserDetector;
        private readonly IUrlService urlShortenerService;
        private readonly ILogger<UrlsController> _logger;

        public UrlsController(ILogger<UrlsController> logger, IBrowserDetector browserDetector, IUrlService urlShortenerService)
        {
            this.browserDetector = browserDetector;
            this.urlShortenerService = urlShortenerService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var urls = await this.urlShortenerService.GetAll();

            var model = new HomeViewModel
            {
                Urls = urls
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(string originalUrl)
        {
            try
            {
                var shortUrl = await this.urlShortenerService.ShortenUrlAsync(originalUrl);

                TempData["Notice"] = "Your url has been shorted successfully. Please view it in the list below.";
            }
            catch (UrlShortnerException e)
            {
                TempData["Notice"] = e.Message;
            }
            catch (Exception)
            {
                TempData["Notice"] = "Sorry, we found an unexpected error. Try again later.";
            }

            return RedirectToAction("Index");
        }

        [Route("/{url}")]
        public async Task<IActionResult> Visit(string url)
        {
            var model = await this.urlShortenerService.GetByShortUrl(url);

            if (model == null)
                return NotFound();

            await this.urlShortenerService.SaveClickMetrics(url, this.browserDetector.Browser.Name, this.browserDetector.Browser.OS);

            var prefix = model.OriginalUrl.StartsWith("http") ? string.Empty : "http://";

            return Redirect($"{prefix}{model.OriginalUrl}");
        }

        [Route("urls/{url}")]
        public async Task<IActionResult> Show(string url)
        {
            var model = await this.urlShortenerService.GetByShortUrl(url);

            if (model == null)
                return NotFound();

            return View(new ShowViewModel
            {
                Url = model,
                DailyClicks = await this.urlShortenerService.CountClicksPerDayInCurrentMontByShortUrl(url),
                BrowseClicks = await this.urlShortenerService.CountClicksPerBrowserInCurrentMontByShortUrl(url),
                PlatformClicks = await this.urlShortenerService.CountClicksPerPlatformInCurrentMontByShortUrl(url)
            });
        }
    }
}

hey-url-challenge-code-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/materialize/css/materialize.min.css" />
    <script src="~/lib/materialize/js/materialize.min.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a class="brand-logo" asp-area="" asp-controller="Urls" asp-action="Index">HeyURL!</a>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

hey-url-challenge-code-dotnet/Views/Urls/Index.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

@if (TempData["Notice"] is not null)
{
    <div class="card-panel notice deep-orange">@TempData["Notice"]</div>
}

<div class="row">
    <div class="col m12">
        <form asp-action="Create">
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col m8 offset-m2 center-align">
                            <span class="card-title">Create a new short URL</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m6 offset-m2">
                            <input type="text" class="validate form-control" name="originalUrl" placeholder="Your original URL here"/>
                        </div>
                        <div class="col m2">
                            <button type="submit" class="btn">Shorten URL</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@if (Model.Urls?.Any() ?? false)
{
    <table class="table highlight">
        <thead>
            <tr>
                <th scope="col">Short URL</th>
                <th scope="col">Original URL</th>
                <th scope="col">Created</th>
                <th scope="col">Clicks Count</th>
                <th scope="col">Stats</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var url in Model.Urls)
            {
                var prefix = url.OriginalUrl.StartsWith("http") ? string.Empty : "http://";

                <tr>
                    <th scope="row">
                        <a href="@string.Format("/{0}", url.ShortUrl)" target="_self">@($"{Context.Request.Host}/{url.ShortUrl}")</a>
                    </th>
                    <td><a href="@($"{prefix}{url.OriginalUrl}")" target="_blank">@url.OriginalUrl</a></td>
                    <td>@url.CreatedAt.ToString("MMM") @url.CreatedAt.ToString("dd"), @url.CreatedAt.ToString("yyyy")</td>
                    <td>@url.Count</td>
                    <td>
                        <a href=@string.Format("/urls/{0}", url.ShortUrl)>
                            <svg class="octicon octicon-graph" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">
                                <path fill-rule="evenodd" d="M16 14v1H0V0h1v14h15zM5 13H3V8h2v5zm4 0H7V3h2v10zm4 0h-2V6h2v7z"></path>
                            </svg>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

hey-url-challenge-code-dotnet/Views/Urls/Show.cshtml
@model hey_url_challenge_code_dotnet.ViewModels.ShowViewModel

@{
    ViewBag.Title = "Show";
    Layout = "_Layout";
}

<div class="row">
    <div class="col s12">
      <ul class="card-panel collection with-header">
        <li class="collection-header">
          <h4>
            Stats for <a href="@Model.Url.ShortUrl">@Model.Url.ShortUrl</a>
          </h4>
        </li>
        <li class="collection-item">Created May 22, 2021</li>
        <li class="collection-item">
            Original URL: @Model.Url.OriginalUrl
        </li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <div class="card-panel">
        <div id="total-clicks-chart"></div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s6">
      <div class="card-panel">
        <div id="platforms-chart"></div>
      </div>
    </div>

    <div class="col s6">
      <div class="card-panel">
        <div id="browsers-chart"></div>
      </div>
    </div>
  </div>

  <script>
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(drawCharts);
    function drawTotalClicksChart() {
      var data = google.visualization.arrayToDataTable([
        ['day', 'clicks'],
      ].concat(@Json.Serialize(Model.DailyClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'total clicks',
        haxis: {
          title: 'day of month'
        },
        vaxis: {
          title: 'clicks'
        }
      };
      var chart = new google.visualization.AreaChart(
        document.getElementById('total-clicks-chart')
      );
      chart.draw(data, options);
    }
    function drawBrowsersChart() {
      var data = google.visualization.arrayToDataTable([
        ['browser', 'clicks'],
      ].concat(@Json.Serialize(Model.BrowseClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'Browsers'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('browsers-chart')
      );
      chart.draw(data, options);
    }
    function drawPlatformsChart() {
      var data = google.visualization.arrayToDataTable([
        ['platform', 'clicks'],
      ].concat(@Json.Serialize(Model.PlatformClicks.Select(e => new object[] { e.Key, e.Value }))));
      var options = {
        title: 'Platform'
      };
      var chart = new google.visualization.PieChart(
        document.getElementById('platforms-chart')
      );
      chart.draw(data, options);
    }
    function drawCharts() {
      drawTotalClicksChart();
      drawBrowsersChart();
      drawPlatformsChart();
    }
  </script>